🛠️ Improve docker scripts 🛠️ Add job to dispose redundant item images

diff --git a/Docker/build b/Docker/build
--- a/Docker/build
+++ b/Docker/build
@@ -1,15 +1,25 @@
 #!/bin/bash
+project=Wishlist
 version=$1
+label=$(echo "$project" | tr "[:upper:]" "[:lower:]")
 
-if [[ ! -d "./Wishlist.xcodeproj" ]] ; then
-  echo "Script must be run in project directory"; exit 1
+echo
+
+if [[ ! -d "./$project.xcodeproj" ]] ; then
+  echo "🤔 Script must be run in project directory ..."; exit 1
 fi
 if [[ ! $version =~ ^[0-9]+(\.[0-9]+){2,2}(\-RC[0-9]+){0,1}$ ]];
 then
-  echo "Script must be run with version number as argument"; exit 1
+  echo "🤔 Script must be run with version number as argument ..."; exit 1
 fi
 
-echo " #### Building Docker image for project Wishlist with version $version"
+echo "🐳 BUILDING Docker image for project $project with version $version"
 
-docker build -f Docker/docker -t "wishlist:$version" .
+out=$(docker build -f Docker/docker -t "$label:$version" . 2>&1)
+[ $? -ne 0 ] \
+    && echo "$out" \
+    && echo "⛔ Docker build command failed!" \
+    && exit 1
 
+image=$(docker image ls | grep " $version " | tr -s ' ' | cut -d' ' -f 1,2,3)
+echo "😎 BUILD $image"
